---
development:
  url: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: false

production:
  url: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: true
  
test:
  url: <%= ENV['CLOUDINARY_URL'] %>
  enhance_image_tag: true
  static_file_support: false
